import type { Metadata } from "next";
import "./globals.css";
import LanguageLoader from "@/components/modules/layouts/LanguageLoader";
import "react-datepicker/dist/react-datepicker.css";
import {
  Inter,
  Playfair_Display,
  Plus_Jakarta_Sans,
  Lexend_Exa,
  Roboto,
} from "next/font/google";
import { Toaster } from "react-hot-toast";
import Script from "next/script";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-sc",
  weight: ["400", "700"],
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const lexendExa = Lexend_Exa({
  subsets: ["latin"],
  variable: "--font-lexend-exa",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Restaurant Reservation",
  description: "Generated by Restaurant Reservation",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${roboto.variable} ${lexendExa.variable} ${inter.variable} ${jakarta.variable} antialiased`}
      >
        <LanguageLoader />
        <Toaster position="top-right" reverseOrder={false} />
        {children}

        {/* Google Analytics */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-3DK4DTG5KH"
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-3DK4DTG5KH');
          `}
        </Script>
      </body>
    </html>
  );
}
