import type { Metadata } from "next";
import "./globals.css";
import LanguageLoader from "@/components/modules/layouts/LanguageLoader";
import "react-datepicker/dist/react-datepicker.css";
import {
  Inter,
  Playfair_Display,
  Plus_Jakarta_Sans,
  Lexend_Exa,
  Roboto,
} from "next/font/google";
import { Toaster } from "react-hot-toast";

export const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto", // <- để dùng với tailwind
  display: "swap",
});
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-sc",
  weight: ["400", "700"],
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // dùng với className tailwind
  display: "swap",
});

export const lexendExa = Lexend_Exa({
  subsets: ["latin"],
  variable: "--font-lexend-exa", // để dùng class tailwind nếu muốn
  weight: ["400", "500", "600", "700"], // thêm các độ đậm cần dùng
});

export const metadata: Metadata = {
  title: "Restaurant Reservation",
  description: "Generated by Restaurant Reservation",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${roboto.variable} ${lexendExa?.variable} ${inter?.variable} ${jakarta.variable} antialiased`}
      >
        <LanguageLoader />
        <Toaster position="top-right" reverseOrder={false} />
        {children}
      </body>
    </html>
  );
}
